name: Cleanup-Old-Artifacts

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 18 * * *
    
jobs: 
  Cleanup-Old-Artifacts:
    runs-on: ubuntu-18.04
    steps:
    - name: Cleanup Old Action Artifacts
      uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ github.token }}
        expire-in: 3d
        
  Cleanup-Workflow-Runs:
    needs: Cleanup-Old-Artifacts
    runs-on: ubuntu-18.04
    steps:
      - name: Cleanup Workflow Runs
        uses: GitRML/delete-workflow-runs@v1.2.1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          
  Cleanup-old-Releases:
    needs: Cleanup-Workflow-Runs
    runs-on: ubuntu-18.04
    steps:
      - name: Cleanup-old-Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 7
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
